import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import Providers from "../components/Provider";
import { getServerSession, Session } from "next-auth";
import { authConfig } from "../auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default async function RootLayout(props: { children: ReactNode }) {
   const session = (await getServerSession(authConfig)) as Session;
   const cookie = headers().get("cookie") as string;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session} cookie={cookie}>
          {props.children}
        </Providers>
      </body>
    </html>
  );
}